### ISSUE TITLE
Option to use this on Heroku

### ISSUE THREAD

**Issue by besi** [yamldb/yaml_db#63]
Is there a way to push a dump to [heroku](https://heroku.com)?

**Comment by besi** [comment]
@dnrce this would certainly cover my usecase for a one-time thing, however, if I regularly want to pull and push data to heroku I guess this would be too cumbersome. I am more thinking of an automated way to do this.

I am in a similar position now with another project so I will look for options to do this.

**Comment by dnrce** [comment]
Another way to rapidly switch the database configuration is to make use of the `DATABASE_URL` environment variable locally -- something like ``DATABASE_URL=`heroku config:get DATABASE_URL` bundle exec rake db:data:load`` might do the trick.

**Comment by besi** [comment]
@dnrce This did not work, with the help of your feedback I got it working:

- Run `heroku config:get DATABASE_URL` to get the pg url
- Configure the `database.yml` production according to the `DATABASE_URL:

    ```yaml
    # heroku config:get DATABASE_URL
    # postgres://yyyy:xxxx@something.compute-1.amazonaws.com:5432/zzzz
    production:
      adapter: postgresql
      username: yyyy
      password: xxxx
      host: something.compute-1.amazonaws.com
      port: 5432
      database: zzzzz
    ```
- Create a dump and load it into the development db

        RAILS_ENV=production  bin/rake db:data:dump`
        bin/rake db:data:load`
